language: python
python:
  - "2.7"
#  - "3.2" # 3.2 is broken, for some reason
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt -r requirements.test.txt
# command to run tests, e.g. python setup.py test
script: nosetests --with-coverage --cover-package=flask_s3
after_success: coveralls
sudo: false
